Repository eslint/rewrite, pull requests merged in 2024-10, with the labels that each got.

#123 feat: Add `Language.defaultLanguageOptions`
  packages/core/src/types.ts
Labels: feature, accepted

#122 docs: Use prerendered sponsors for README
  README.md
  package.json
  packages/compat/README.md
  packages/config-array/README.md
  packages/core/README.md
  packages/migrate-config/README.md
  packages/object-schema/README.md
  packages/plugin-kit/README.md
  tools/update-readme.js
Labels: documentation, accepted

#59 fix!: correctly detect if file is outside base path on Windows
  .npmrc
  packages/config-array/README.md
  packages/config-array/fix-std__path-imports.js
  packages/config-array/jsr.json
  packages/config-array/package.json
  packages/config-array/rollup.std__path-config.js
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug, accepted, breaking

#126 ci: add Node.js v23
  .github/workflows/ci.yml
Labels: build

#110 feat: Add rule types
  packages/core/package.json
  packages/core/src/types.ts
Labels: feature
