Repository eslint/rewrite, pull requests merged in 2024-08, with the labels that each got.

#90 chore: setup typescript-eslint
  eslint.config.js
  package.json
  packages/core/src/types.ts
  packages/object-schema/src/types.ts
Labels: chore

#101 feat: Export ObjectSchema
  packages/config-array/src/index.js
Labels: feature

#102 feat: add CommonJS `core` types
  packages/core/jsr.json
  packages/core/package.json
Labels: feature

#108 docs: Add workaround if npx fails
  packages/migrate-config/README.md
Labels: documentation

#99 feat: Add plugin-kit package
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/change.yml
  .github/workflows/release-please.yml
  .release-please-manifest.json
  packages/core/src/types.ts
  packages/plugin-kit/CHANGELOG.md
  packages/plugin-kit/LICENSE
  packages/plugin-kit/README.md
  packages/plugin-kit/jsr.json
  packages/plugin-kit/package.json
  packages/plugin-kit/rollup.config.js
  packages/plugin-kit/src/@types/levn.d.ts
  packages/plugin-kit/src/config-comment-parser.js
  packages/plugin-kit/src/index.js
  packages/plugin-kit/src/source-code.js
  packages/plugin-kit/src/types.ts
  packages/plugin-kit/tests/config-comment-parser.test.js
  packages/plugin-kit/tests/source-code.test.js
  packages/plugin-kit/tsconfig.esm.json
  packages/plugin-kit/tsconfig.json
  release-please-config.json
Labels: feature, accepted

#109 chore: Add .ts files to lint-staged
  package.json
Labels: chore

#113 chore: remove `release-as` for plugin-kit
  release-please-config.json
Labels: chore

#112 feat: Add Directive and DirectiveType
  packages/core/src/types.ts
  packages/plugin-kit/README.md
  packages/plugin-kit/src/index.js
  packages/plugin-kit/src/source-code.js
  packages/plugin-kit/tests/source-code.test.js
Labels: feature, accepted
