Repository eslint/rewrite, pull requests merged in 2024-06, with the labels that each got.

#40 ci: build packages in Verify Files job
  .github/workflows/ci.yml
Labels: build

#38 chore: remove unused rollup dev dependencies
  packages/migrate-config/package.json
Labels: chore

#39 chore: remove non-existing files from `jsr.json`
  packages/compat/jsr.json
Labels: chore

#37 fix: Wrap plugins that are wrapped in extends
  packages/migrate-config/src/migrate-config.js
  packages/migrate-config/tests/fixtures/basic-eslintrc/expected.cjs
  packages/migrate-config/tests/fixtures/basic-eslintrc/expected.mjs
  packages/migrate-config/tests/fixtures/no-globals-for-env/expected.cjs
  packages/migrate-config/tests/fixtures/no-globals-for-env/expected.mjs
  packages/migrate-config/tests/fixtures/plugins-dedupe/.eslintrc.yml
  packages/migrate-config/tests/fixtures/plugins-dedupe/expected.cjs
  packages/migrate-config/tests/fixtures/plugins-dedupe/expected.mjs
  packages/migrate-config/tests/fixtures/release-it/expected.cjs
  packages/migrate-config/tests/fixtures/release-it/expected.mjs
  packages/migrate-config/tests/migrate-config-cli.test.js
Labels: bug

#45 docs: Update migrate-config README
  packages/migrate-config/README.md
Labels: documentation

#48 fix: Add 'main' and 'types' entries to package.json
  packages/compat/package.json
  packages/config-array/package.json
  packages/object-schema/package.json
Labels: bug

#43 refactor: Use `eslint-config-eslint` for linting this repo
  eslint.config.js
  package.json
  packages/compat/src/fixup-rules.js
  packages/compat/src/index.js
  packages/compat/tests/fixup-rules.js
  packages/compat/tests/rules/prefer-rest-params.js
  packages/compat/tests/rules/require-atomic-updates.js
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
  packages/migrate-config/src/migrate-config-cli.js
  packages/migrate-config/src/migrate-config.js
  packages/migrate-config/src/types.ts
  packages/migrate-config/tests/migrate-config-cli.test.js
  packages/object-schema/src/index.js
  packages/object-schema/src/merge-strategy.js
  packages/object-schema/src/object-schema.js
  packages/object-schema/src/types.ts
  packages/object-schema/src/validation-strategy.js
  packages/object-schema/tests/merge-strategy.js
  packages/object-schema/tests/object-schema.js
  packages/object-schema/tests/validation-strategy.js
  scripts/build.js
  tools/dedupe-types.js
Labels: chore

#47 feat: Add includeIgnoreFile() method
  .github/workflows/release-please.yml
  packages/compat/README.md
  packages/compat/src/fixup-rules.js
  packages/compat/src/ignore-file.js
  packages/compat/src/index.js
  packages/compat/tests/fixtures/ignore-files/gitignore1.txt
  packages/compat/tests/ignore-file.js
  packages/migrate-config/package.json
  packages/migrate-config/src/migrate-config.js
Labels: feature, accepted

#50 fix!: treat `*` as a universal pattern
  packages/config-array/README.md
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug, accepted, breaking

#52 docs: Decision docs for start of rewrite
  decisions/000-template.md
  decisions/001-rewrite-core.md
  decisions/002-javascript-jsdoc-tsc.md
  decisions/003-esm.md
Labels: documentation, accepted

#56 chore: automate adding sponsors section to readme
  .github/workflows/update-readme.yml
  README.md
  package.json
  packages/compat/README.md
  packages/config-array/README.md
  packages/migrate-config/README.md
  packages/object-schema/README.md
  tools/commit-readme.sh
  tools/update-readme.js
Labels: chore, accepted

#60 docs: add `@eslint/migrate-config` to README
  README.md
Labels: documentation

#63 chore: add tech sponsors
  README.md
  packages/compat/README.md
  packages/config-array/README.md
  packages/migrate-config/README.md
  packages/object-schema/README.md
  tools/update-readme.js
Labels: chore, accepted

#61 fix!: Allow escaping characters on Windows
  packages/config-array/package.json
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug, accepted, breaking

#71 chore: add platinum tier size
  tools/update-readme.js
Labels: chore

#70 fix: skip add plugin when already imported
  packages/migrate-config/src/migrate-config.js
  packages/migrate-config/tests/fixtures/import-duplicate/.eslintrc.cjs
  packages/migrate-config/tests/fixtures/import-duplicate/expected.cjs
  packages/migrate-config/tests/fixtures/import-duplicate/expected.mjs
  packages/migrate-config/tests/migrate-config-cli.test.js
Labels: bug

#75 chore: add `jsr.json` to `.prettierignore`
  .prettierignore
Labels: chore, accepted

#77 docs: Add decision document around type definitions
  decisions/004-types.md
Labels: documentation
