Repository eslint/rewrite, pull requests merged in 2024-07, with the labels that each got.

#85 build: switch to `googleapis/release-please-action`
  .github/workflows/release-please.yml
Labels: build

#81 feat: Add more type definitions
  packages/core/src/types.ts
Labels: feature

#86 ci: Publish packages with provenance
  .github/workflows/release-please.yml
Labels: build

#92 fix: `basePath` directory can never be ignored
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug

#91 feat: `eslint-plugin-react` supports ESLint v9
  packages/migrate-config/src/compat-plugins.js
  packages/migrate-config/tests/fixtures/import-duplicate/.eslintrc.cjs
  packages/migrate-config/tests/fixtures/import-duplicate/expected.cjs
  packages/migrate-config/tests/fixtures/import-duplicate/expected.mjs
Labels: feature

#94 chore: upgrade `@types/eslint` to v9
  eslint.config.js
  packages/compat/package.json
  packages/compat/src/fixup-rules.js
  packages/core/package.json
  packages/migrate-config/package.json
  packages/migrate-config/src/migrate-config.js
Labels: chore
