Repository eslint/rewrite, pull requests merged in 2024-11, with the labels that each got.

#132 fix: non-optional properties in generic interfaces
  packages/core/src/types.ts
Labels: bug

#133 chore: fix formatting error
  packages/plugin-kit/tests/config-comment-parser.test.js
Labels: chore

#131 feat: Add Language#normalizeLanguageOptions()
  packages/core/src/types.ts
Labels: feature

#117 chore: fully type check packages/*/src files
  CONTRIBUTING.md
  package.json
  packages/compat/tsconfig.json
  packages/config-array/tsconfig.json
  packages/core/tsconfig.json
  packages/migrate-config/tsconfig.json
  packages/object-schema/tsconfig.json
  packages/plugin-kit/package.json
  packages/plugin-kit/src/@types/levn.d.ts
  packages/plugin-kit/src/config-comment-parser.js
  packages/plugin-kit/tsconfig.json
  scripts/build.js
  tsconfig.base.json
  tsconfig.json
Labels: chore

#135 fix: Update RuleVisitor type
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  decisions/001-rewrite-core.md
  decisions/004-types.md
  package.json
  packages/compat/README.md
  packages/config-array/README.md
  packages/core/src/types.ts
  packages/migrate-config/README.md
  packages/object-schema/README.md
  packages/plugin-kit/README.md
Labels: bug, accepted
