Repository eslint/rewrite, pull requests merged in 2024-05, with the labels that each got.

#6 ci: fix a typo in release-please-config.json
  release-please-config.json
Labels: build

#5 feat: @eslint/compat package
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/change.yml
  .github/workflows/release-please.yml
  .release-please-manifest.json
  packages/compat/CHANGELOG.md
  packages/compat/LICENSE
  packages/compat/README.md
  packages/compat/jsr.json
  packages/compat/package.json
  packages/compat/rollup.config.js
  packages/compat/src/fixup-rules.js
  packages/compat/src/index.js
  packages/compat/src/types.ts
  packages/compat/tests/fixtures/rules/consistent-this.js
  packages/compat/tests/fixtures/rules/global-require.js
  packages/compat/tests/fixtures/rules/handle-callback-err.js
  packages/compat/tests/fixtures/rules/no-lone-blocks.js
  packages/compat/tests/fixtures/rules/no-loop-func.js
  packages/compat/tests/fixtures/rules/prefer-rest-params.js
  packages/compat/tests/fixtures/rules/require-atomic-updates.js
  packages/compat/tests/fixup-rules.js
  packages/compat/tests/rules/consistent-this.js
  packages/compat/tests/rules/global-require.js
  packages/compat/tests/rules/handle-callback-err.js
  packages/compat/tests/rules/no-lone-blocks.js
  packages/compat/tests/rules/no-loop-func.js
  packages/compat/tests/rules/prefer-rest-params.js
  packages/compat/tests/rules/require-atomic-updates.js
  packages/compat/tsconfig.cjs.json
  packages/compat/tsconfig.esm.json
  packages/compat/tsconfig.json
  release-please-config.json
Labels: feature, accepted

#9 fix: Add bootstrap SHA to release-please config
  release-please-config.json
Labels: bug

#3 feat: Add types to config-array
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  package.json
  packages/config-array/jsr.json
  packages/config-array/package.json
  packages/config-array/src/base-schema.js
  packages/config-array/src/config-array.js
  packages/config-array/src/files-and-ignores-schema.js
  packages/config-array/src/types.ts
  packages/config-array/tsconfig.cjs.json
  packages/object-schema/tsconfig.cjs.json
  scripts/build.js
  tools/dedupe-types.js
Labels: feature

#10 build: avoid unnecessary steps in release-please workflow
  .github/workflows/release-please.yml
Labels: build

#12 feat: sync packages meta
  packages/compat/jsr.json
  packages/compat/package.json
  packages/config-array/package.json
  packages/object-schema/jsr.json
  packages/object-schema/package.json
Labels: feature

#13 fix: Minor change to trigger new releases
  packages/compat/CHANGELOG.md
  packages/config-array/CHANGELOG.md
  packages/object-schema/CHANGELOG.md
Labels: bug

#14 ci: Test in Node.js 22
  .github/workflows/ci.yml
Labels: build

#17 docs: add `@eslint/compat` package to README
  README.md
Labels: documentation

#18 docs: update config-array installation instructions
  packages/config-array/README.md
Labels: documentation

#16 fix: npm and JSR package contents
  packages/compat/jsr.json
  packages/compat/package.json
  packages/config-array/jsr.json
  packages/config-array/package.json
  packages/object-schema/jsr.json
  packages/object-schema/package.json
  tools/prepend-type-ref.js
Labels: bug, accepted

#22 chore: format all files
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  .prettierignore
  README.md
  eslint.config.js
  package.json
  packages/compat/README.md
  packages/compat/jsr.json
  packages/compat/src/types.ts
  packages/compat/tsconfig.cjs.json
  packages/compat/tsconfig.esm.json
  packages/config-array/README.md
  packages/config-array/jsr.json
  packages/config-array/rollup.config.js
  packages/config-array/src/index.js
  packages/config-array/src/types.ts
  packages/config-array/tests/config-array.test.js
  packages/config-array/tsconfig.cjs.json
  packages/config-array/tsconfig.esm.json
  packages/object-schema/README.md
  packages/object-schema/jsr.json
  packages/object-schema/rollup.config.js
  packages/object-schema/src/merge-strategy.js
  packages/object-schema/src/object-schema.js
  packages/object-schema/src/types.ts
  packages/object-schema/src/validation-strategy.js
  packages/object-schema/tests/merge-strategy.js
  packages/object-schema/tests/object-schema.js
  packages/object-schema/tests/validation-strategy.js
  packages/object-schema/tsconfig.cjs.json
  packages/object-schema/tsconfig.esm.json
  release-please-config.json
Labels: chore

#23 chore: Simplify type generation
  .github/workflows/ci.yml
  package.json
  packages/compat/package.json
  packages/compat/rollup.config.js
  packages/compat/tsconfig.cjs.json
  packages/config-array/package.json
  packages/config-array/rollup.config.js
  packages/config-array/tsconfig.cjs.json
  packages/object-schema/package.json
  packages/object-schema/rollup.config.js
  packages/object-schema/tsconfig.cjs.json
  tools/prepend-type-ref.js
Labels: chore, accepted, build

#29 chore: Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#27 fix: ConfigObject type
  packages/config-array/src/config-array.js
  packages/config-array/src/types.ts
Labels: bug

#7 feat!: add method `getConfigStatus`, update `isFileIgnored`
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: feature, accepted, breaking

#32 fix: YAML syntax in release script
  .github/workflows/release-please.yml
Labels: bug

#33 fix: Update and standardize READMEs
  packages/compat/README.md
  packages/config-array/README.md
  packages/object-schema/README.md
Labels: bug

#35 fix: release-please tweets
  .github/workflows/release-please.yml
Labels: bug

#36 fix: add code coverage npm scripts
  .c8rc
  packages/compat/package.json
  packages/config-array/package.json
  packages/object-schema/package.json
Labels: bug, chore

#31 chore: add .github/renovate.json5
  .github/renovate.json5
Labels: chore
