Repository eslint/rewrite, pull requests merged in 2025-03, with the labels that each got.

#161 chore: Update first config-helpers version
  release-please-config.json
Labels: chore

#167 feat: Look up flat/ config alternatives in defineConfig
  packages/config-helpers/src/define-config.js
  packages/config-helpers/tests/define-config.test.js
Labels: feature, accepted

#169 chore: Remove hardcoded version
  release-please-config.json
Labels: chore

#162 feat: normalize patterns to handle "./" prefix in files and ignores
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug, feature, contributor pool

#171 test: fix error message checking
  packages/config-array/tests/config-array.test.js
Labels: chore, accepted
