Repository eslint/rewrite, pull requests merged in 2025-05, with the labels that each got.

#197 fix: Upgrade @eslint/core
  packages/compat/package.json
  packages/config-helpers/package.json
  packages/plugin-kit/package.json
  release-please-config.json
Labels: bug

#195 chore: Add triage:no to release PR
  release-please-config.json
Labels: chore, accepted

#202 chore: Update package.json template to include directory
  templates/package/package.json
Labels: chore, accepted

#203 ci: run tests in Node.js 24
  .github/workflows/ci.yml
Labels: build

#199 build: Fix JSR publish for eslint/core
  packages/core/package.json
Labels: build

#209 chore: remove unused `@ts-ignore` comment
  package.json
  packages/compat/package.json
  packages/config-helpers/package.json
  packages/config-helpers/src/define-config.js
  packages/migrate-config/package.json
  templates/package/package.json
Labels: chore

#213 refactor: update and fix error types in JSDoc comments
  packages/config-array/src/config-array.js
  packages/config-helpers/src/define-config.js
  packages/config-helpers/src/global-ignores.js
  packages/object-schema/src/object-schema.js
  packages/plugin-kit/src/source-code.js
Labels: chore
