Repository eslint/rewrite, pull requests merged in 2025-08, with the labels that each got.

#235 fix: relax type for rule.meta.docs.recommended
  packages/config-helpers/tests/types/types.test.ts
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: bug, accepted, contributor pool

#254 ci: create `stale.yml`
  .github/workflows/stale.yml
Labels: accepted, build

#212 feat: add support for `getLocFromIndex` and `getIndexFromLoc`
  packages/plugin-kit/README.md
  packages/plugin-kit/src/source-code.js
  packages/plugin-kit/tests/source-code.test.js
  packages/plugin-kit/tests/types/types.test.ts
Labels: feature, accepted

#253 refactor: update eslint-config-eslint
  package.json
  packages/compat/src/ignore-file.js
  packages/migrate-config/src/migrate-config.js
  packages/plugin-kit/src/config-comment-parser.js
  tools/update-readme.js
Labels: chore, accepted, contributor pool
