Repository eslint/rewrite, pull requests merged in 2025-04, with the labels that each got.

#173 feat: Set type for RuleDefinition.defaultOptions
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: feature, accepted

#178 feat: add core types for language-specific rule definitions
  package.json
  packages/core/package.json
  packages/core/src/types.ts
  packages/core/tests/types/tsconfig.json
  packages/core/tests/types/types.test.ts
Labels: feature, accepted

#182 feat: make `TextSourceCodeBase` a generic type
  packages/core/src/types.ts
  packages/plugin-kit/src/source-code.js
  packages/plugin-kit/tests/types/types.test.ts
Labels: feature, accepted, contributor pool

#172 feat: Better conversion of .eslintrc.js files in migrate-config
  packages/migrate-config/package.json
  packages/migrate-config/src/migrate-config-cli.js
  packages/migrate-config/src/migrate-config.js
  packages/migrate-config/tests/fixtures/backend-nx-skeleton-esm-js/.eslintrc.mjs
  packages/migrate-config/tests/fixtures/backend-nx-skeleton-esm-js/expected.mjs
  packages/migrate-config/tests/fixtures/backend-nx-skeleton-js/.eslintrc.cjs
  packages/migrate-config/tests/fixtures/backend-nx-skeleton-js/expected.cjs
  packages/migrate-config/tests/fixtures/formidable-js/.eslintrc.cjs
  packages/migrate-config/tests/fixtures/formidable-js/LICENSE
  packages/migrate-config/tests/fixtures/formidable-js/expected.cjs
  packages/migrate-config/tests/fixtures/import-duplicate-js/.eslintrc.cjs
  packages/migrate-config/tests/fixtures/import-duplicate-js/expected.cjs
  packages/migrate-config/tests/fixtures/import-duplicate/expected.mjs
  packages/migrate-config/tests/fixtures/prisma-js/.eslintignore
  packages/migrate-config/tests/fixtures/prisma-js/.eslintrc.cjs
  packages/migrate-config/tests/fixtures/prisma-js/LICENSE
  packages/migrate-config/tests/fixtures/prisma-js/expected.cjs
  packages/migrate-config/tests/fixtures/prisma/expected.cjs
  packages/migrate-config/tests/migrate-config-cli.test.js
Labels: feature, accepted, tsc waiting

#183 chore: Separate pull requests
  release-please-config.json
Labels: chore, accepted

#189 chore: fix release-please PR title
  release-please-config.json
Labels: chore
