Repository eslint/rewrite, pull requests merged in 2025-06, with the labels that each got.

#87 ci: Test in Bun
  .github/workflows/bun-test.yml
  .gitignore
  packages/config-array/tests/config-array.test.js
Labels: build

#218 fix: explicit match in array elements of `files`
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug, accepted

#210 feat: Add extendable config types
  eslint.config.js
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: feature, accepted

#220 fix: consider negated patterns universal
  packages/config-array/src/config-array.js
  packages/config-array/tests/config-array.test.js
Labels: bug, accepted

#222 docs: fix bun command and update documentation
  packages/compat/README.md
  packages/config-array/README.md
  packages/config-helpers/README.md
  packages/object-schema/README.md
  packages/plugin-kit/README.md
Labels: documentation, accepted

#228 fix: Allow RuleConfig to have array with just severity
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: bug, accepted

#215 fix: relax `@eslint/compat` eslint peerDependencies constraint
  packages/compat/package.json
Labels: bug
