Repository eslint/rewrite, pull requests merged in 2025-09, with the labels that each got.

#260 chore: update eslint-config-eslint
  package.json
Labels: chore, accepted

#269 docs: correct bun installation command and use `defineConfig` in README
  packages/compat/README.md
  templates/package/README.md
Labels: documentation

#277 ci: workaround for CI failure on Windows with Bun
  package.json
Labels: build

#278 test: use `strictEqual` in `plugin-kit` where possible
  packages/plugin-kit/tests/source-code.test.js
Labels: chore
