Repository eslint/rewrite, pull requests merged in 2025-01, with the labels that each got.

#140 feat: Check messageIds in context.report()
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: feature, accepted

#146 fix: Make meta.replacedBy read only
  packages/core/src/types.ts
Labels: bug

#148 fix: CommonJS types in all packages
  eslint.config.js
  packages/compat/package.json
  packages/config-array/package.json
  packages/object-schema/package.json
  packages/plugin-kit/build-cts.js
  packages/plugin-kit/package.json
  tools/build-cts.js
Labels: bug, accepted

#149 feat: Update RuleDefinition for frozen and deprecations
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: feature

#150 feat: Update RuleDefinition with `meta.defaultOptions`
  packages/core/src/types.ts
  packages/core/tests/types/types.test.ts
Labels: feature
